kind: Deployment
apiVersion: apps/v1
metadata:
  name: file-upload-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload-spring-boot-app
  template:
    metadata:
      labels:
        app: file-upload-spring-boot-app
    spec:
      containers:
        - name: file-upload-spring-boot
          image: file-upload-service:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: file-upload-spring-boot-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: file-upload-spring-boot-app