spring.application.name=file-upload-service
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

# H2 DB-Configuration
spring.h2.console.enabled=true
spring.datasource.password=viks
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Oracle DB-Configuration
#spring.datasource.url=jdbc:oracle:thin:@localhost:1527/FREEPDB1
#spring.datasource.username=bank_db
#spring.datasource.password=bank_db
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
