spring.application.name=file-upload-service
spring.h2.console.enabled=true
#spring.datasource.password=viks
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
